---
# HassUnpauseTimer - default

language: "lb"
data:
  - sentences:
      - "(maach|loos) [den] Timer weider"
      - "setz [den] Timer fort"
    example: "maach den Timer weider"
    response: "default"
