---
# HassMediaPause - default
# context_area: true

language: "de-CH"
data:
  - sentences:
      - "(p(a|o)usier|stop[p]|schtop[p]|ahalte|aahalte)"
      - "(p(a|o)usier|stop[p]|schtop[p]) [(d |ds |di |mini )](Musig|Video|Film|Ton) [<hier>]"
      - "[(d |ds |di |mini )](Musig|Video|Film|Ton) [<hier> ](p(a|o)usiere|schtoppe|ahalte|aahalte)"
    example: "pousier d Musig"
    response: "context"
