---
# HassCancelAllTimers - default

language: "ga"
data:
  - sentences:
      - "<timer_cancel> (na hamadóirí go léir|gach amadóir)"
    example: "cealaigh na hamadóirí go léir"
    response: "default"
