---
language: "is"
data:
  - sentences:
      - "(gerðu hlé á|settu í bið|stöðvaðu) [tónlistinni|myndbandinu|myndinni|spilun] [<here>]"
      - "(gerðu hlé|pása) [<here>]"
    example: "gerðu hlé á tónlistinni"
    response: "default"
