---
# HassMediaNext - default
# example: 다음 곡
# context_area: true

language: "ko"
data:
  - sentences:
      - "[<here>] 다음 (곡|노래|트랙|화) [재생|틀어|틀어줘]"
      - "[<here>] 다음 (곡|노래|트랙|화)[으로|로] 넘겨[줘]"
    example: "다음 곡"
    response: "default"
