---
# HassGetCurrentTime - default

language: "vi"
data:
  - sentences:
      - "[bây giờ là] mấy giờ [rồi]"
      - "giờ hiện tại [là mấy giờ]"
    example: "bây giờ là mấy giờ"
    response: "default"
