---
# HassGetCurrentDate - default

language: "af"
data:
  - sentences:
      - "wat is (die|vandag se) [huidige] datum [vandag]"
      - "watter datum is dit [vandag]"
      - "gee my die datum"
    example: "wat is die datum"
    response: "default"
