---
# HassTimerStatus - default

language: "ga"
data:
  - sentences:
      - "cé mhéad ama atá fágtha [ar [<the>] [t-]amadóir]"
      - "cén t-am atá fágtha [ar [<the>] [t-]amadóir]"
    example: "cé mhéad ama atá fágtha ar an amadóir"
    response: "default"
