---
# HassMediaUnpause - default
# context_area: true

language: "uk"
data:
  - sentences:
      - "(зніми з паузи|продовж[и|уй]|віднови) [музику|відео|фільм|відтворення] [<here>]"
    example: "продовжи музику"
    response: "default"
