---
# HassMediaUnpause - default
# example: 다시 재생
# context_area: true

language: "ko"
data:
  - sentences:
      - "[<here>] [음악|영상|비디오] (다시 재생|계속 재생|이어서 재생|재개|재개해|계속해)"
    example: "다시 재생"
    response: "default"
