---
# HassMediaNext - default
# context_area: true

language: "sl"
data:
  - sentences:
      - "[predvajaj] naslednj(o|i|e) [pesem|skladbo|oddajo|element|posnetek|epizodo|komad] [<here>]"
      - "preskoči [na naslednj(i|o|a|e)] [pesem|skladbo|komad|epizodo] [<here>]"
    example: "naslednja pesem"
    response: "default"
