---
# HassGetWeather - default
# example: 오늘 날씨 어때

language: "ko"
data:
  - sentences:
      - "[오늘] [바깥] 날씨 (어때|어때요|알려줘|말해줘)"
      - "[오늘] 날씨 <what_is>"
    example: "오늘 날씨 어때"
    response: "default"
