---
# HassMediaUnpause - default
# context_area: true

language: "ne"
data:
  - sentences:
      - "[<here>] [संगीत|गीत|भिडियो] फेरि सुरु <do_v>"
      - "[<here>] [संगीत|गीत|भिडियो] जारी <do_v>"
    example: "संगीत फेरि सुरु गर्नु"
    response: "default"
