---
# HassGetCurrentTime - default

language: "af"
data:
  - sentences:
      - "hoe laat is dit [nou]"
      - "wat is die [huidige] tyd"
      - "gee my die tyd"
    example: "hoe laat is dit"
    response: "default"
