---
# HassMediaUnpause - default
# context_area: true

language: "vi"
data:
  - sentences:
      - "(phát tiếp|tiếp tục|chạy tiếp) [nhạc|video|phim] [<here>]"
    example: "phát tiếp nhạc"
    response: "default"
