---
# HassUnpauseTimer - default

language: "af"
data:
  - sentences:
      - "(hervat|herbegin) [<the>] <timer_noun>"
      - "gaan voort met [<the>] <timer_noun>"
    example: "hervat die tydhouer"
    response: "default"
