---
# HassMediaNext - default
# context_area: true

language: "af"
data:
  - sentences:
      - "volgende (snit|liedjie|baan|item)"
      - "slaan [hierdie] (snit|liedjie|baan) oor"
      - "speel die volgende (snit|liedjie|baan)"
    example: "volgende snit"
    response: "default"
