---
# HassMediaPause - default
# context_area: true

language: "uk"
data:
  - sentences:
      - "(постав на паузу|[при]зупини) [музику|відео|фільм|відтворення] [<here>]"
      - "пауза"
    example: "постав на паузу музику"
    response: "default"
