---
# HassMediaPause - default
# context_area: true

language: "af"
data:
  - sentences:
      - "pouseer"
      - "hou op speel"
      - "stop [met] speel"
    example: "pouseer"
    response: "default"
