---
language: pt-BR
data:
  - sentences:
      - "[(qual|que) [é] ][o |a ](estado d|tempo restante n)(o|os) [meus |os |os meus ]<timer>"
      - "quanto tempo (falta|resta) (nos|para os) [meus |os |os meus ]<timer>"
    example: "qual o estado dos temporizadores"
    response: "default"
