---
# HassMediaPause - default
# context_area: true

language: "sv"
data:
  - sentences:
      - "pausa [musiken | filmen | videon | uppspelningen] [<here>]"
      - "(paus | stoppa uppspelningen)"
    example: "pausa musiken"
    response: "default"
