---
# HassGetCurrentTime - default
# example: 지금 몇 시야

language: "ko"
data:
  - sentences:
      - "[지금] (몇 시야|몇 시지|몇 시인가요)"
      - "[지금] 시간 (알려줘|말해줘|뭐야)"
    example: "지금 몇 시야"
    response: "default"
