---
# HassGetCurrentDate - default
# example: 오늘 날짜 뭐야

language: "ko"
data:
  - sentences:
      - "[오늘] 날짜 (뭐야|알려줘|말해줘)"
      - "오늘 (며칠이야|며칠이지|며칠인가요)"
    example: "오늘 날짜 뭐야"
    response: "default"
