---
# HassPauseTimer - default

language: "af"
data:
  - sentences:
      - "pouseer [<the>] <timer_noun>"
      - "wag met [<the>] <timer_noun>"
    example: "pouseer die tydhouer"
    response: "default"
