---
# HassCancelAllTimers - default

language: "cs"
data:
  - sentences:
      - "<timer_cancel> (všechn[a|y]|vešker[á|é]) [mé|má] [běžící] <casovac>"
    example: "zruš všechny časovače"
    response: "default"
