---
# HassMediaPause - default
# context_area: true

language: "vi"
data:
  - sentences:
      - "(tạm dừng|dừng) [nhạc|video|phim|phát] [<here>]"
    example: "tạm dừng nhạc"
    response: "default"
