---
language: "lv"
data:
  - sentences:
      - "nākam(ā|o) (dziesma|dziesmu|celiņu|sēriju|epizodi) [<here>]"
      - "pārslēdz uz nākamo [<here>]"
    example: "nākamā dziesma"
    response: "default"
