---
language: "hi"
data:
  - sentences:
      - "[<here>] अगला <media_next_item> [<media_play>]"
      - "[<here>] <media_next_item> <media_skip>"
      - "[<here>] (अगला | आगे) <media_play>"
      - "[<here>] (स्किप करो | स्किप कर दो | नेक्स्ट करो)"
    example: "अगला गाना"
    response: "default"
