---
# HassMediaNext - default
# context_area: true

language: "sv"
data:
  - sentences:
      - "[spela ]nästa [spår | låt | avsnitt] [<here>]"
      - "hoppa (över | till nästa) [spår | låt | avsnitt] [<here>]"
    example: "nästa spår"
    response: "default"
