---
language: "lt"
data:
  - sentences:
      - "(pristabdy(k|ti)|sustabdy(k|ti)) [muziką|vaizdo įrašą|filmą|grojimą] [<here>]"
      - "pauzė [<here>]"
    example: "pristabdyk muziką"
    response: "default"
