---
# HassMediaNext - default
# context_area: true

language: "vi"
data:
  - sentences:
      - "(bài|mục|tập) [hát] (tiếp theo|kế tiếp) [<here>]"
      - "chuyển sang (bài|mục|tập) [hát] (tiếp theo|kế tiếp) [<here>]"
    example: "bài hát tiếp theo"
    response: "default"
