---
# HassClimateGetTemperature - default
# context_area: true

language: "af"
data:
  - sentences:
      - "wat is die [huidige] temperatuur [<here>]"
      - "hoe warm is dit [<here>]"
      - "hoe koud is dit [<here>]"
    example: "wat is die temperatuur"
    response: "default"
