---
# HassTimerStatus - default

language: "vi"
data:
  - sentences:
      - "còn bao (nhiêu|lâu) [thời gian] [nữa] [trên [cái] hẹn giờ]"
      - "[cái] hẹn giờ còn bao lâu"
    example: "còn bao lâu nữa"
    response: "default"
