---
# HassMediaUnpause - default
# context_area: true

language: "sv"
data:
  - sentences:
      - "(återuppta | fortsätt) [med] [musiken | filmen | videon | uppspelningen] [<here>]"
    example: "återuppta musiken"
    response: "default"
