---
# HassMediaPlayerMute - default
# example: ztlum
# context_area: true

language: "cs"
data:
  - sentences:
      - "(<ztlumit_zvuk>;[<tady>])"
      - "((<ztlumit_zvuk>|<vypnout>) <zvuk_media>;[<tady>])"
    example: "ztlum"
    response: "default"
