# HassGetCurrentDate - default
# example: আজ কত তারিখ

language: "bn"
data:
  - sentences:
      - "[আজ | আজকের] তারিখ কত"
      - "আজ কত তারিখ"
      - "আজ (কী | কি | কোন) বার"
      - "আজ (কী | কি) তারিখ"
      - "আমাকে [আজকের] তারিখ বলো"
    example: "আজ কত তারিখ"
    response: "default"
