---
# HassGetWeather - default

language: "de"
data:
  - sentences:
      - "wie ist[ das] Wetter[ heute]"
      - "Wetter[bericht][ heute]"
    example: "wie ist das Wetter"
    response: "default"
  - sentences:
      - "wie (warm|kalt) ist es ([dr]au(ss|ß)en|heute)"
      - "wie[ ]viel (Grad|°) (sind es|haben wir) ([dr]au(ss|ß)en|heute)"
    example: "wie warm ist es draußen"
    response: "outside_temp"
