---
language: "hi"
data:
  - sentences:
      - "[आज] [बाहर] मौसम (कैसा है | क्या है | कैसा रहेगा)"
      - "(आज का | बाहर का) मौसम (कैसा है | क्या है | बताओ)"
      - "मौसम (बताओ | बताइए | बता दो)"
      - "[आज का] वेदर (कैसा है | क्या है | बताओ)"
    example: "मौसम कैसा है"
    response: "default"
