---
# HassGetCurrentTime - default
# example: what time is it

language: "de"
data:
  - sentences:
      - "uhrzeit"
      - "wie spät[ (ist es|haben wir)]"
      - "(wie viel|wieviel) uhr[ (ist es|haben wir|hat es)]"
      - "(nenn[e]|gib|gebe|sag[e]|verrat[e]) mir die[ aktuelle] uhrzeit"
    example: "wie spät ist es"
    response: "default"
