---
language: cy
data:
  - sentences:
      - "(oedia|oedi|stopia)[ <y>|<y>] (cerddoriaeth|gerddoriaeth|fideo|ffilm) [<yma>]"
      - "(oedia|oedi|stopia) [<yma>]"
    example: "oedi'r gerddoriaeth"
    response: "default"
