---
language: "is"
data:
  - sentences:
      - "(haltu áfram með|spilaðu áfram) [tónlistinni|myndbandinu|myndinni|spilun] [<here>]"
    example: "haltu áfram með tónlistinni"
    response: "default"
