---
# HassCancelAllTimers - default
# example: 모든 타이머 취소

language: "ko"
data:
  - sentences:
      - "(<all>|전체) 타이머 <timer_cancel>"
      - "타이머 (전부|모두) <timer_cancel>"
    example: "모든 타이머 취소"
    response: "default"
