---
# HassMediaNext - default
# context_area: true

language: "he"
data:
  - sentences:
      - "[ה](שיר|רצועה|פרק) [ה]בא [<here>]"
      - "דלג [ל(שיר|רצועה|פרק) הבא] [<here>]"
    example: "השיר הבא"
    response: "default"
