---
# HassTimerStatus - default

language: "lb"
data:
  - sentences:
      - "wéi vill Zäit ass nach iwwreg [um Timer]"
      - "wéi laang leeft den Timer nach"
    example: "wéi vill Zäit ass nach iwwreg"
    response: "default"
