---
language: cy
data:
  - sentences:
      - "(ailddechreua|ailddechrau|parhau â|parha â)[ <y>|<y>] (cerddoriaeth|gerddoriaeth|fideo|ffilm) [<yma>]"
    example: "ailddechrau'r gerddoriaeth"
    response: "default"
