---
language: "fa"
data:
  - sentences:
      - "[از] (تایمر|تایمرم) چقدر [زمان] (باقی مانده|مانده)"
      - "چقدر زمان (باقی مانده|مانده)"
      - "وضعیت (تایمر|تایمرها|تایمرهایم)"
    example: "چقدر زمان باقی مانده"
    response: "default"
