---
language: "is"
data:
  - sentences:
      - "hvað er (mikið|langt) eftir [af tímamælinum]"
      - "hversu langur tími er eftir [af tímamælinum]"
    example: "hvað er mikið eftir"
    response: "default"
