---
# HassMediaUnpause - default
# context_area: true

language: "he"
data:
  - sentences:
      - "(המשך|חדש|נגן) [את] [ה](מוזיקה|נגינה|וידאו|סרט) [<here>]"
    example: "המשך את המוזיקה"
    response: "default"
