---
language: "fa"
data:
  - sentences:
      - "دما (چند است|چنده|چقدر است|چقدره)"
      - "دمای <here> (چند است|چنده|چقدر است|چقدره)"
      - "[<here>] چند درجه است"
    example: "دما چند است"
    response: "default"
