---
# HassFanSetSpeed - default
# example: nastav ventilátor na 50 %
# slots: {percentage}
# context_area: true

language: "cs"
data:
  - sentences:
      - "[<nastavit>] (<fan_sg>|<fan_pl>) na <fan_speed>"
      - "[<nastavit>] rychlost (<fan_gen_sg>|<fan_gen_pl>) na <fan_speed>"
    example: "nastav ventilátor na 50 %"
    response: "default"
