---
# HassUnpauseTimer - default

language: "ga"
data:
  - sentences:
      - "atosaigh [<the>] [t-]amadóir"
      - "lean ar aghaidh leis [<the>] [t-]amadóir"
    example: "atosaigh an t-amadóir"
    response: "default"
