---
# HassMediaUnpause - default
# context_area: true

language: "lb"
data:
  - sentences:
      - "(maach|loos) [d'](Musek|Video|Film|Ofspillen) [<here>] weider"
    example: "maach d'Musek weider"
    response: "default"
