---
# HassMediaPause - default
# context_area: true

language: "sl"
data:
  - sentences:
      - "(zaustavi|pavza|premor)"
      - "zaustavi [predvajanje|glasbo|video|film] [<here>]"
      - "daj [glasbo|video|film] [<here>] na (pavzo|premor)"
    example: "zaustavi predvajanje"
    response: "default"
