---
# HassMediaPause - default
# context_area: true

language: "lb"
data:
  - sentences:
      - "pauséier [d'](Musek|Video|Film|Ofspillen) [<here>]"
      - "pauséier [<here>]"
    example: "pauséier d'Musek"
    response: "default"
