---
language: "hi"
data:
  - sentences:
      - "(सभी | सारे | सब) टाइमर <timer_cancel>"
      - "(सभी | सारे | सब) (टाइमरों | टाइमर) को <timer_cancel>"
    example: "सभी टाइमर रद्द करो"
    response: "default"
