---
language: "hi"
data:
  - sentences:
      - "आज (कौन सी | क्या) <date_word> है"
      - "आज की <date_word> क्या है"
      - "<date_word> क्या है [आज]"
      - "[आज] कितनी तारीख है"
      - "[आज [की]] <date_word> (बताओ | बताइए | बता दो)"
    example: "आज की तारीख क्या है"
    response: "default"
