---
# HassTimerStatus - default
# example: 타이머 얼마나 남았어

language: "ko"
data:
  - sentences:
      - "[타이머] (얼마나 남았어|얼마 남았어|얼마나 남았나요)"
      - "타이머 (상태|확인|어때)"
    example: "타이머 얼마나 남았어"
    response: "default"
