---
# HassMediaPause - default
# example: 일시정지
# context_area: true

language: "ko"
data:
  - sentences:
      - "[<here>] [음악|영상|비디오] (일시정지|일시 정지|일시정지해|멈춰|정지|정지해)"
    example: "일시정지"
    response: "default"
