# HassGetCurrentTime - default
# example: এখন কয়টা বাজে

language: "bn"
data:
  - sentences:
      - "[এখন] কয়টা বাজে"
      - "কয়টা বাজছে"
      - "[এখন] সময় কত"
      - "সময় কত হয়েছে"
      - "ঘড়িতে [এখন] কয়টা বাজে"
      - "[আমাকে] [বর্তমান | এখনকার] সময় বলো"
      - "বর্তমান সময় কত"
    example: "এখন কয়টা বাজে"
    response: "default"
