---
# HassGetCurrentTime - default
# example: समय क्या है

language: "hi"
data:
  - sentences:
      - "[अभी [का]] [वर्तमान] (समय | वक्त | टाइम) क्या है"
      - "[अभी [का]] [वर्तमान] (समय | वक्त | टाइम) क्या हुआ है"
      - "[अभी [का]] [वर्तमान] (समय | वक्त | टाइम) (क्या | कितना) हो रहा है"
      - "घड़ी में क्या (समय | वक्त | टाइम) हो रहा है"
      - "[अभी] कितने बजे हैं"
      - "[अभी] कितने बज रहे हैं"
      - "[अभी [का]] (समय | वक्त | टाइम) बताओ"
    example: "समय क्या है"
    response: "default"
