---
# HassMediaPlayerUnmute - default
# example: zruš ztlumení
# context_area: true

language: "cs"
data:
  - sentences:
      - "(zruš[it] ztlumení [[multimediálního ]přehrávače];[<tady>])"
      - "(odtlum[it];[<tady>])"
      - "((odtlum[it]|obnov[it]|vrať|vrátit|<zapnout>) <zvuk_media>;[<tady>])"
    example: "zruš ztlumení"
    response: "default"
