---
# HassMediaNext - default
# context_area: true

language: "lb"
data:
  - sentences:
      - "nächst (Lidd|Titel|Episod) [<here>]"
      - "spring op dat nächst [Lidd|Titel|Episod] [<here>]"
    example: "nächst Lidd"
    response: "default"
