---
language: "hi"
data:
  - sentences:
      - "[मेरे] टाइमर (में | का) कितना (समय | टाइम) (बाकी | बचा) है"
      - "कितना (समय | टाइम) (बाकी | बचा) है"
      - "[मेरा] टाइमर कितना (बाकी | बचा) है"
      - "[मेरे] टाइमर (की स्थिति | का स्टेटस) (क्या है | बताओ)"
      - "कितने टाइमर चल रहे हैं"
      - "[मेरे] टाइमर कैसे चल रहे हैं"
    example: "कितना समय बाकी है"
    response: "default"
