---
language: "fa"
data:
  - sentences:
      - "[امروز] چه (تاریخی|روزی) است"
      - "تاریخ [امروز] (چیست|چیه|چنده)"
      - "امروز چندم است"
    example: "امروز چه تاریخی است"
    response: "default"
