---
# HassMediaPause - default
# context_area: true

language: "he"
data:
  - sentences:
      - "(השהה|השהי|עצור|עצרי|הפסק|הפסיקי) [את] [ה](מוזיקה|נגינה|וידאו|סרט) [<here>]"
    example: "השהה את המוזיקה"
    response: "default"
