---
language: cy
data:
  - sentences:
      - "faint o amser sydd ar ôl [ar[ <y>|<y>] amserydd]"
      - "pa mor hir sydd ar ôl [ar[ <y>|<y>] amserydd]"
    example: "faint o amser sydd ar ôl"
    response: "default"
