---
# HassMediaUnpause - default
# context_area: true

language: "de-CH"
data:
  - sentences:
      - "(wyter|wiiter)(schpile|mache|lose|luege)"
      - "[(d |ds |di |mini )](Musig|Video|Film|Ton) [<hier> ]((wyter|wiiter)(schpile|mache|lose|luege)|fortsetze)"
      - "(mach|schpiu|spiu) [(d |ds |di |mini )](Musig|Video|Film|Ton) [<hier> ](wyter|wiiter)"
    example: "d Musig wyterschpile"
    response: "context"
